name: 'Terraform Plan Commenter'
description: 'Post a plan as a PR comment'
inputs:
  plan-file:
    description: 'Path to plan.txt'
    required: true
    default: 'terraform/plan.txt'
runs:
  using: 'node20'
  main: 'index.js'
